---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.6-alpine

inputs:
- name: source-code
  path: gopath/src/github.com/ECSTeam/twitter-resource

outputs:
- name: build-output

run:
  path: gopath/src/github.com/ECSTeam/twitter-resource/ci/tasks/build-source.sh
