---
jobs:
- name: build-resource-image
  plan:
  - get: source-code
    trigger: true
  - task: build-resource
    file: source-code/ci/tasks/build-resource.yml
  - put: docker-hub
    params:
      build: build-output


resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:ECSTeam/twitter-resource.git
    branch: master
    private_key: {{github-private-key}}
- name: docker-hub
  type: docker-image
  source:
    repository: jghiloni/twitter-concourse-resource
    email: jghiloni@ecsteam.com
    username: jghiloni
    password: {{docker-hub-password}}
